# Generated by Django 3.2.19 on 2023-05-21 02:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_id', models.IntegerField(unique=True)),
                ('num_of_seats', models.IntegerField()),
                ('seat_cost', models.IntegerField()),
                ('seat_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
            options={
                'ordering': ['seat_id'],
            },
        ),
    ]
