# Generated by Django 3.2.19 on 2023-05-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('date_booked', models.DateTimeField()),
                ('seat_booked', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['date_booked'],
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='total_tables',
            field=models.IntegerField(default=0),
        ),
    ]
