# Generated by Django 3.2.19 on 2023-06-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(max_length=5)),
                ('booking_client_name', models.CharField(max_length=30)),
                ('booking_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['booking_code'],
            },
        ),
    ]
