# Generated by Django 3.2.19 on 2023-06-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_delete_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
