# Generated by Django 3.2.19 on 2023-06-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20230601_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['seat_code']},
        ),
        migrations.RemoveField(
            model_name='seat',
            name='num_of_seats',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_cost',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_id',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='total_tables',
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_code',
            field=models.CharField(default='TXXX', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_desc',
            field=models.CharField(default='No description available', max_length=120),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_persons',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='seat',
            name='seats_max',
            field=models.IntegerField(default=2),
        ),
    ]
